<a href="https://colab.research.google.com/github/aaryanML/Pytorch/blob/main/nn_Module_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [9]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [10]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [11]:
x_train.shape

(455, 30)

In [12]:
x_test.shape

(114, 30)

## Scaling

In [13]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [14]:
x_train

array([[-0.46130152, -0.23941857, -0.4228243 , ...,  0.37550933,
         0.53625359,  1.06068829],
       [ 1.77857899,  2.01685568,  1.71692078, ...,  0.61510438,
        -0.77745556, -0.02381987],
       [-0.80041829, -0.2417591 , -0.79937971, ..., -0.93934527,
        -1.15682428, -0.3976014 ],
       ...,
       [ 0.26252755, -1.40032316,  0.19621624, ..., -0.52942272,
        -0.69462396, -0.86997458],
       [-0.54394342,  0.61019508, -0.54323927, ...,  0.06526447,
         0.10884254,  0.48159777],
       [ 0.43066107,  0.86999429,  0.52932295, ...,  1.33849711,
         0.6091454 ,  2.24703836]])

## Encoding

In [15]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [16]:
y_train

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [17]:
type(x_train)

numpy.ndarray

## Convert Numpy to Pytorch Tensors

In [28]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [29]:
type(x_train_tensor)

torch.Tensor

## Define Model

In [33]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid(),
    )

  def forward(self,features):
    out = self.network(features)

    return out

In [34]:
epochs = 50
learning_rate = 0.1

In [35]:
loss_function = nn.BCELoss()

In [49]:
# create model
model = MySimpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
# model.parameters() => returns an iterator containing all learnable weights and biases that PyTorch computes gradients for and updates during training.

for epoch in range(epochs):
  # forward pass
  y_pred = model(x_train_tensor)

  # calculate loss
  loss = loss_function(y_pred,y_train_tensor.view(-1,1))
  # .view is same as .reshape in numpy
  # -1 tells the .view to decide the shape at that position on its own

  # clear gradients => so that gradients dont accumulate
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6814230680465698
Epoch: 2, Loss: 0.6591104865074158
Epoch: 3, Loss: 0.6359586715698242
Epoch: 4, Loss: 0.6104726195335388
Epoch: 5, Loss: 0.5848972201347351
Epoch: 6, Loss: 0.5602282285690308
Epoch: 7, Loss: 0.5376757979393005
Epoch: 8, Loss: 0.5166215896606445
Epoch: 9, Loss: 0.4969521462917328
Epoch: 10, Loss: 0.47868484258651733
Epoch: 11, Loss: 0.46163803339004517
Epoch: 12, Loss: 0.4454774260520935
Epoch: 13, Loss: 0.4302175045013428
Epoch: 14, Loss: 0.4156855642795563
Epoch: 15, Loss: 0.40191206336021423
Epoch: 16, Loss: 0.3887985944747925
Epoch: 17, Loss: 0.37631210684776306
Epoch: 18, Loss: 0.36434295773506165
Epoch: 19, Loss: 0.3528793156147003
Epoch: 20, Loss: 0.3418562412261963
Epoch: 21, Loss: 0.33123716711997986
Epoch: 22, Loss: 0.3210105895996094
Epoch: 23, Loss: 0.31114521622657776
Epoch: 24, Loss: 0.3016890585422516
Epoch: 25, Loss: 0.2926087975502014
Epoch: 26, Loss: 0.28390300273895264
Epoch: 27, Loss: 0.27556389570236206
Epoch: 28, Loss: 0.26755768060684204
Epoch: 29, Loss: 0.25988849997520447
Epoch: 30, Loss: 0.2525469660758972
Epoch: 31, Loss: 0.24553804099559784
Epoch: 32, Loss: 0.23886370658874512
Epoch: 33, Loss: 0.232497900724411
Epoch: 34, Loss: 0.22643066942691803
Epoch: 35, Loss: 0.22068774700164795
Epoch: 36, Loss: 0.21528570353984833
Epoch: 37, Loss: 0.21014387905597687
Epoch: 38, Loss: 0.20525234937667847
Epoch: 39, Loss: 0.20059968531131744
Epoch: 40, Loss: 0.19617772102355957
Epoch: 41, Loss: 0.1919754594564438
Epoch: 42, Loss: 0.18797066807746887
Epoch: 43, Loss: 0.18413995206356049
Epoch: 44, Loss: 0.1804899126291275
Epoch: 45, Loss: 0.17701217532157898
Epoch: 46, Loss: 0.17369163036346436
Epoch: 47, Loss: 0.1705193817615509
Epoch: 48, Loss: 0.16748614609241486
Epoch: 49, Loss: 0.16458426415920258
Epoch: 50, Loss: 0.16180463135242462

In [47]:
! pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [48]:
from torchinfo import summary

summary(model,input_size=(455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 3]                  93
│    └─ReLU: 2-2                         [455, 3]                  --
│    └─Linear: 2-3                       [455, 1]                  4
│    └─Sigmoid: 2-4                      [455, 1]                  --
==========================================================================================
Total params: 97
Trainable params: 97
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.04
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.01
Params size (MB): 0.00
Estimated Total Size (MB): 0.07
==========================================================================================

## Printing Models weights and biases

In [39]:
for name,param in model.named_parameters():
  print(name)
  print(param)

network.0.weight
Parameter containing:
tensor([[ 0.1527, -0.0064,  0.0702,  0.2246,  0.2052,  0.2101,  0.0237,  0.2498,
         -0.0065, -0.0324,  0.1001, -0.1721, -0.0256, -0.1028,  0.1165,  0.1156,
         -0.0188, -0.0309,  0.1208,  0.0098,  0.2741,  0.1394,  0.2932, -0.0122,
         -0.0691,  0.0505,  0.1782,  0.2976, -0.0304,  0.0130],
        [ 0.2065,  0.2644,  0.2607,  0.2584,  0.1155,  0.0344,  0.0558, -0.0205,
          0.0597, -0.1162,  0.0484, -0.0192,  0.1566,  0.0450, -0.1406,  0.1010,
         -0.1283,  0.1051, -0.1299, -0.0777,  0.2912,  0.1510, -0.0103,  0.2720,
          0.1729,  0.0304,  0.1438,  0.1979, -0.0450,  0.0984],
        [-0.0558, -0.0518,  0.2410, -0.0395,  0.1605,  0.1935,  0.1788,  0.0813,
          0.0250,  0.0448, -0.0810,  0.0542, -0.0837,  0.1496,  0.1580, -0.0710,
         -0.0863,  0.0106, -0.1424, -0.1845,  0.2589,  0.1595,  0.1718,  0.1918,
          0.0055,  0.2101,  0.2013,  0.2020,  0.0741,  0.1140]],
       requires_grad=True)
network.0.bias
Parameter containing:
tensor([-0.0594,  0.1429,  0.1976], requires_grad=True)
network.2.weight
Parameter containing:
tensor([[0.6719, 0.7444, 0.6115]], requires_grad=True)
network.2.bias
Parameter containing:
tensor([-0.9995], requires_grad=True)

# Model Evaluation

In [46]:
with torch.no_grad():
  y_pred = model(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'accuracy : {accuracy.item():.4f}')

accuracy : 0.5711