<a href="https://colab.research.google.com/github/aaryanML/Pytorch/blob/main/5.%20NN_in_PyTorch_using_Dataset_%26_DataLoaders.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [4]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [7]:
x_train.shape

(455, 30)

In [8]:
y_train.shape

(455,)

## Standard Scaler

In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
x_train

array([[-0.48703147, -0.80457048, -0.39726358, ...,  0.91038981,
         1.73593324,  2.24053856],
       [ 1.11510458,  0.61274106,  1.04223919, ..., -0.35491983,
        -0.88050294, -1.01641598],
       [ 2.66032639,  1.17366403,  2.60035733, ...,  1.44548248,
        -0.51782862, -0.3630317 ],
       ...,
       [ 0.56872781,  0.54349131,  0.57934999, ...,  0.25074971,
         0.91829693, -0.42892384],
       [ 0.92728757,  1.47143795,  0.92238395, ..., -0.0767639 ,
        -2.12071959, -0.87244995],
       [-0.78298556, -1.93103307, -0.77873388, ..., -0.38920881,
         0.16704298,  0.07163496]])

## Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0])

## Convert Numpy Arrays to Pytorch Tensors

In [36]:
x_train_tensor = torch.from_numpy(x_train).float()
y_train_tensor = torch.from_numpy(y_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [37]:
type(x_train_tensor)

torch.Tensor

## Dataset and DataLoaders

Dataset : Defines how to access individual samples from a dataset.\
DataLoader : Loads samples from a Dataset and provides them in batches during training.

In [38]:
from torch.utils.data import Dataset,DataLoader

# Dataset is an abstract class
# you have to implement __init__ , __len__ and __getitem__ functions in your class
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [39]:
train_dataset = CustomDataset(x_train_tensor,y_train_tensor)
test_dataset = CustomDataset(x_test_tensor,y_test_tensor)

In [30]:
train_dataset[1]

(tensor([ 1.1151,  0.6127,  1.0422,  1.0381, -1.6103, -0.3442,  0.2809,  0.2294,
         -0.1850, -1.3586,  0.8090,  0.1614,  0.6979,  0.7424, -0.4972,  1.5576,
          1.0579,  0.4369,  0.1026,  0.5089,  0.7087, -0.1451,  0.6414,  0.5914,
         -1.9373, -0.3675, -0.0740, -0.3549, -0.8805, -1.0164],
        dtype=torch.float64),
 tensor(1))

In [40]:
# Dataloader
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

## Define Model

In [41]:
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    return self.network(features)

In [47]:
epochs = 25
learning_rate = 0.01

In [48]:
# create model
model = MySimpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loss function
loss_function = nn.BCELoss()

## Training Pipeline

In [50]:
for epoch in range(epochs):
  for batch_features,batch_labels in train_loader:
    # forward pass
    y_pred = model(batch_features)

    # calculate loss
    loss = loss_function(y_pred,batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch : {epoch+1} , loss : {loss.item()}')

Epoch : 1 , loss : 0.08149023354053497
Epoch : 2 , loss : 0.2258850336074829
Epoch : 3 , loss : 0.24484394490718842
Epoch : 4 , loss : 0.17770686745643616
Epoch : 5 , loss : 0.27166748046875
Epoch : 6 , loss : 0.20941565930843353
Epoch : 7 , loss : 0.23854565620422363
Epoch : 8 , loss : 0.06581669300794601
Epoch : 9 , loss : 0.180083230137825
Epoch : 10 , loss : 0.12969282269477844
Epoch : 11 , loss : 0.05836963653564453
Epoch : 12 , loss : 0.0942874327301979
Epoch : 13 , loss : 0.1747664362192154
Epoch : 14 , loss : 0.14466632902622223
Epoch : 15 , loss : 0.16383373737335205
Epoch : 16 , loss : 0.20166194438934326
Epoch : 17 , loss : 0.21733173727989197
Epoch : 18 , loss : 0.0756334662437439
Epoch : 19 , loss : 0.054762136191129684
Epoch : 20 , loss : 0.5248286724090576
Epoch : 21 , loss : 0.02559359185397625
Epoch : 22 , loss : 0.09166146069765091
Epoch : 23 , loss : 0.02256438322365284
Epoch : 24 , loss : 0.08215073496103287
Epoch : 25 , loss : 0.08657550811767578

## Model Evaluation using test_loader

In [51]:
model.eval()
# model.eval() switches the model to evaluation mode, changing the behaviour of layers like Dropout and BatchNorm for inference.

accuracy_list = []

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
    y_pred = model(batch_features)
    # Convert probabilities to binary predictions
    y_pred = (y_pred > 0.5).float()

    # calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean()
    accuracy_list.append(batch_accuracy)

# calculate overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'accuracy_list : {overall_accuracy}')

accuracy_list : 0.9626736044883728