<a href="https://colab.research.google.com/github/aaryanML/Pytorch/blob/main/SimpleNN_from_Scratch_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## train_test_split

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [7]:
x_train.shape

(455, 30)

## Scaling

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
x_train

array([[-1.23532287, -0.54939737, -1.21191708, ..., -0.93039867,
        -0.62464568,  0.03994912],
       [ 1.27022917,  0.13957764,  1.13125693, ...,  0.20597558,
        -0.56827939, -1.48586923],
       [-0.37184634, -0.84664746, -0.34606613, ..., -0.20787621,
        -1.5099281 , -0.70927183],
       ...,
       [-0.6103911 , -0.33279653, -0.66664764, ..., -1.3095885 ,
        -1.22478096, -0.75955511],
       [ 0.08305296, -0.00789527,  0.06198318, ..., -0.29393347,
        -0.72743128, -0.52154756],
       [ 2.04688651,  0.66955842,  2.07414374, ...,  1.8912637 ,
         1.52224707,  0.93499159]])

## Label Encoding

In [10]:
y_train

110    B
277    M
284    B
48     B
562    M
      ..
550    B
314    B
327    B
448    B
393    M
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1])

## Convert Numpy Arrays to Pytorch Tensors

In [13]:
x_train_tensor = torch.from_numpy(x_train)
y_train_tensor = torch.from_numpy(y_train)
x_test_tensor = torch.from_numpy(x_test)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
x_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

## Defining the Model

In [21]:
class MySimpleNN:
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1 - 1e-7)

    # calculate loss
    loss = (-(y * torch.log(y_pred) + (1-y) * torch.log(1-y_pred))).mean()
    return loss

## Important Parameters

In [26]:
epochs = 25
learning_rate = 0.1

## Training Pipeline

In [27]:
# create model
model = MySimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)

  # calculate loss
  loss = model.loss_function(y_pred,y_train_tensor,)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    # if we dont disable gradient tracking, then pytorch will add this operation below in the the computation graph
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradient => so that gradients dont accumulate
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch : {epoch + 1} , Loss : {loss.item()}')

Epoch : 1 , Loss : 3.678735925019033
Epoch : 2 , Loss : 3.558197166222865
Epoch : 3 , Loss : 3.4298881735169333
Epoch : 4 , Loss : 3.2897051971272604
Epoch : 5 , Loss : 3.1474798017095353
Epoch : 6 , Loss : 2.9988047413480468
Epoch : 7 , Loss : 2.843427822767176
Epoch : 8 , Loss : 2.680985013512282
Epoch : 9 , Loss : 2.513551762888526
Epoch : 10 , Loss : 2.3416336668038906
Epoch : 11 , Loss : 2.168722025800401
Epoch : 12 , Loss : 1.9989900299820411
Epoch : 13 , Loss : 1.8288591268025471
Epoch : 14 , Loss : 1.6669262613128766
Epoch : 15 , Loss : 1.510647471412291
Epoch : 16 , Loss : 1.3588475570418992
Epoch : 17 , Loss : 1.2230988857501865
Epoch : 18 , Loss : 1.1059100556140025
Epoch : 19 , Loss : 1.0090474197249792
Epoch : 20 , Loss : 0.93293984857203
Epoch : 21 , Loss : 0.8762760906350977
Epoch : 22 , Loss : 0.836101374299892
Epoch : 23 , Loss : 0.8085306336690607
Epoch : 24 , Loss : 0.7897267293087782
Epoch : 25 , Loss : 0.7765942165253116

In [28]:
model.weights

tensor([[ 0.4268],
        [-0.0694],
        [ 0.0687],
        [-0.0786],
        [ 0.4425],
        [ 0.1196],
        [ 0.1017],
        [-0.6356],
        [-0.3387],
        [ 0.1504],
        [ 0.4239],
        [ 0.0022],
        [ 0.1625],
        [-0.1716],
        [ 0.4660],
        [-0.3018],
        [ 0.4807],
        [ 0.1248],
        [-0.1023],
        [-0.1227],
        [ 0.3354],
        [ 0.1593],
        [ 0.3844],
        [-0.4498],
        [ 0.1344],
        [-0.2522],
        [-0.2372],
        [-0.3705],
        [ 0.0010],
        [ 0.2520]], dtype=torch.float64, requires_grad=True)

In [29]:
model.bias

tensor([-0.1161], dtype=torch.float64, requires_grad=True)

## Model Evaluation

In [31]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'accuracy : {accuracy.item():.4f}')

accuracy : 0.5205